#**Precisão**

In [ ]:
#Exercício 02.1
a = 1; s = int(input('Digite um valor: '))

def precision(a, s):
  
  while s > 1:
    a /= 2
    s = 1 + a
  
  prec = 2*a
  print(f'a: {a}, Precisão: {prec}')

precision(a, s)

In [ ]:
#Exercício 02.2
a = 1; val = int(input('Digite um valor: '))

def precision(a, val):
  s = val + a

  while s > val:
    a /= 2
    s = val + a

  prec = 2*a
  print(f'Referência: {val} -> Precisão: {prec}')

precision(a, val)

#**Somatório**

In [ ]:
#Exercício 01

n1 = 100000; x1 = 0.1
n2 = 80000; x2 = 0.125


def soma(n, x):
  p = 0
  for i in range(n):
    p += x

  s = abs(10000 - p) #absuluto
  r = s/10000 #relativo
  print(f'n = {n}, x= {x} --> Erro absoluto: {s}, Erro relativo: {r}')

print('a) n = 100000, x = 0.1')
soma(n1, x1)

print('\nb) n = 80000, x = 0.125')
soma(n2, x2)

#**Serie de Taylor**

In [ ]:
#Exercício 03
import math
from math import factorial as fact

def taylorSeries(n, x):
  e = 0

  if x < 0:
    y = -x
    for k in range(0, n+1):
      e += (y**k)/fact(k)
    return 1/e

  else:
    for k in range(0, n+1):
      e += (x**k)/fact(k)
    return e
print(f'e = {taylorSeries(100, -15)}')

In [ ]:
#2
def taylorSeriesModify(n, x, p='n'):
  e = 0

  if x < 0: #para valores de x negativos
    y = -x
    for k in range(0, n+1):
      if k < 2:
        e_previous = (y**k)/fact(k)
        e += e_previous
      else:
        e_current = e_previous*(y/k)
        if(e  + e_current == float('inf')):
          return e
        e += e_current
        e_previous = e_current
      if e == float('inf'):
        break
    return 1/e

  else: #para valores de x positivos
    for k in range(0, n+1):
      if k < 2:
        e_previous = (x**k)/fact(k)
        e += e_previous
      else:
        e_current = e_previous*(x/k)
        e += e_current
        e_previous = e_current
      if(p in 'sS'):
        print(f'k: {k}, e: {e}')
    return e

In [ ]:
#3
def taylorSeriesModify(n, x, p='n'):
  e = 0

  if x < 0: #para valores de x negativos
    y = -x
    for k in range(0, n+1):
      if k < 2:
        e_previous = (y**k)/fact(k)
        e += e_previous
      else:
        e_current = e_previous*(y/k)
        if(e  + e_current == float('inf')):
          return e
        e += e_current
        e_previous = e_current
      if e == float('inf'):
        break
    return 1/e

  else: #para valores de x positivos
    for k in range(0, n+1):
      if k < 2:
        e_previous = (x**k)/fact(k)
        e += e_previous
      else:
        e_current = e_previous*(x/k)
        if(e  + e_current == float('inf')): #ponto de parada
          return k, e
        e += e_current
        e_previous = e_current
      if(p in 'sS'):
        print(f'k: {k}, e: {e}')
    return k, e

#**Funções Utilizadas**

In [ ]:
#import sympy as sy
#import sympy as sy
#x, y, z = sy.symbols('x y z')
#sy.init_printing(use_unicode=True)
import math


f = lambda x: x**5 - 9*x + 2
#f = lambda x: 2*x**9 + 5*x**7 + x
#f_derivada = lambda x: 18*x**8 + 35*x**6
g = lambda x: math.log10(x**2)
#h = lambda x: 5**x * x
r = lambda x: math.cos(x) * math.sin(x) * math.log10(x)
s = lambda x: 5/x**3 - math.sqrt(x)

def function(f, x):
    return f(x)

#**Localizar Raízes**

In [ ]:
def findRoots(f, I=[-10, 10], step = 1):
  if(len(I) > 2):
    x = I
  else:
    x = []
    for i in range(I[0], I[1]+1):
      x.append(i)

  y = []
  for i in x:
    y.append(f(i))
  
  for i in range(len(x)):
    print(f'x: {x[i]}, y: {y[i]}')

#findRoots(f, [-10, 10])
#findRoots(g, [1, 10])
#findRoots(h, [-5, 5])
#findRoots(r, [1, 10])
#findRoots(s, [1, 10])

#**Método da Bissecção**

In [ ]:
e = 0.000000001
def bisection(f, I):
  p = I[1] - I[0]
  k = 0
  while(abs(function(f, p)) > e):
    p = (I[0]+I[1])/2

    if(function(f, I[0])*function(f, p) < 0):
      I[1] = p
    else:
      I[0] = p
    k += 1

  return (p, k, function(f, p))

func1 = bisection(f, [-10, 10])
print(f'Bissecção --> x: {func1[0]}, k: {func1[1]}, f(x): {func1[2]}')
func2 = bisection(g, [-2, 0])
print(func2)
func3 = bisection(r, [1, 10])
print(func3)

Bissecção --> x: -1.7836475850344868, k: 38, f(x): -1.9609203150139365e-10
(-1.0, 1, 0.0)
(6.283185307634994, 32, 3.6349742622719197e-10)


#**Método do Ponto Fixo**

In [ ]:
import math
def fi(x):
  return (x**5 + 2) / 9


def mpf(x0, prec):
  if abs(function(f,x0)) < prec:
    res = function(f, x0)
  
  while True:
    k = 1
    x1 = fi(x0)

    if abs(function(f, x1)) < prec or abs(x1 - x0) < prec:
      res = x1
      return [res, k]

    x0 = x1
    k += 1


x0 = float(input("Digite o X0: "))
prec = 0.00001

func1 = mpf(x0, prec)
print(f'Ponto Fixo --> x: {func1[0]}, k: {func1[1]}')

Digite o X0: 0
Ponto Fixo --> x: 0.22228243586776333, k: 1


#**Método de Secante**

In [ ]:
e = 0.000000001
def secante(f, x0, x1):
  k = 1
  if(abs(function(f, x0)) < e):
    return (x0, k)
  if(abs(function(f, x1)) < e or abs(x1 - x0) < e):
    return (x1, k)
  
  while True:
    x2 = x1 - ((function(f, x1))/(function(f, x1) - function(f, x0))) * (x1 - x0)

    if(abs(function(f, x2)) < e or abs(x2 - x1) < e):
      return (x2, k)
    
    x0 = x1
    x1 = x2
    k += 1

func1 = secante(f, 1.9, 1.8)
print(f'Secante --> x: {func1[0]}, k: {func1[1]}')
func2 = secante(g, -1.3, -1.2)
print(func2)

Secante --> x: 1.6713621679510056, k: 6
(-1.0000000000009641, 5)


#**Método da Posição Falsa**

In [ ]:
e = 0.00000001
def fpm(f, i):
  k = 1
  if((i[1] - i[0]) < e):
    return (i[0], k)


  M = function(f, i[0])
  while True:
    x = (i[0]*function(f, i[1]) - i[1]*function(f, i[0])) / (function(f, i[1]) - function(f, i[0]))

    if(abs(function(f, x)) < e):
      return (x, k)

    if(M*function(f, x) > 0):
      i[0] = x
    else:
      i[1] = x
    
    if((i[1] - i[0]) < e):
      return (i[1], k)
    
    k += 1

func1 = fpm(f, [1, 2])
print(f'Posição Falsa --> x: {func1[0]}, k: {func1[1]}')
func2 = fpm(g, [-2, 0.1])
print(func2)

Posição Falsa --> x: 1.6713621677808461, k: 24
(-1.0000000065069183, 29)


#**Método de Newton-Raphson**

In [ ]:
def function(x, dx=False):
  if(dx):
    f = lambda x: 5*x**4 - 9
    return f(x) #derivada
  f = lambda x: x**5 - 9*x + 2
  return f(x) #f(x)
  
e = 0.000000001

def newtonRaphson(x0):
  k = 1
  if(abs(function(x0)) < e):
    return (x0, k);
  x1 = x0 - (function(x0) / function(x0, True))

  while True:
    x1 = x0 - (function(x0) / function(x0, True))
    if(abs(function(x1)) < e or abs(x1 - x0) < e):
      return (x1, k)
    x0 = x1
    k += k

func1 = newtonRaphson(2)
print(f'Newton-Raphson --> x: {func1[0]}, k: {func1[1]}')

Newton-Raphson --> x: 1.6713621679510269, k: 16


In [ ]:
#Alternativo
def function(boolean, x):
  if(boolean):
    return x**3 - 9*x + 3 #f(x)
  return 3*x**2 - 9 #derivada de f(x)

e = 0.000000001

def newtonRaphson(f, x0):
  k = 1
  if(abs(function(f, x0)) < e):
    return (x0, k);
  x1 = x0 - (function(f, x0) / function(f, x0, True))

  while True:
    x1 = x0 - (function(f, x0) / function(f, x0, True))
    if(abs(function(f, x1)) < e or abs(x1 - x0) < e):
      return (x1, k)
    x0 = x1
    k += k

In [ ]:
'''def differentiateFunction(x, function, dx = 0.00000001):
  return (function(x + dx) - function(x)) / dx'''

def function(f, x, boolean=False, dx = 0.00000001):
  if(boolean):
    return (f(x + dx) - f(x)) / dx #derivada
  return f(x) #f(x)
  
e = 0.000000001

def newtonRaphson(f, x0):
  k = 1
  if(abs(function(f, x0)) < e):
    return (x0, k);
  x1 = x0 - (function(f, x0) / function(f, x0, True))

  while True:
    x1 = x0 - (function(f, x0) / function(f, x0, True))
    if(abs(function(f, x1)) < e or abs(x1 - x0) < e):
      return (x1, k)
    x0 = x1
    k += k

func1 = newtonRaphson(f, 2)
print(f'Newton-Raphson --> x: {func1[0]}, k: {func1[1]}')
func2 = newtonRaphson(g, -2)
print(func2)
func3 = newtonRaphson(r, 1.2)
print(func3)
func4 = newtonRaphson(s, 1.7)
print(func4)

Newton-Raphson --> x: 1.6713621679510278, k: 16
(-0.9999999999718856, 16)
(0.9999999999988062, 16)
(1.583819608766575, 8)


#**Método de Gauss**

In [ ]:
"""a = [[1, -3, 2],
     [-2, 8, -1],
     [4, -6, 5]]
     
b = [11, -15, 29]"""

a = [[3, -4, 1],
     [1, 2, 2],
     [4, 0, -3]]

b = [9, 3, -2]

def gauss(matrix, b):
  n = len(matrix)

  for k in range(0, n-1):
    for i in range(k+1, n):
      m = matrix[i][k]/matrix[k][k]
      matrix[i][k] = 0
      for j in range(k+1, n):
        matrix[i][j] -= m*matrix[k][j]
      b[i] -= m*b[k] 

  x = n * [0]
  for k in range(n-1, -1, -1):
    s = 0
    for j in range(k+1, n):
      s += matrix[k][j] * x[j]
    x[k] = (b[k] - s) / matrix[k][k]

  
  for i in matrix:
    print(i)

  print(f"\nx: {x}")
    
gauss(a,b)

#**Fatoração LU**

In [ ]:
a = [[3, -4, 1],
     [1, 2, 2],
     [4, 0, -3]]

b = [9, 3, -2]

def magalu(matrix, b):
  n = len(matrix)

  p = []
  for i in range(0, n):
    p.append(i)
  
  for k in range(0, n-1):
    pv = abs(matrix[k][k])
    r = k
    for i in range(k+1, n):
      if abs(matrix[i][k]) > pv:
        pv = abs(matrix[i][k])
        r = i

    if pv == 0:
      print("A matrix é singular!")
      return
    if r != k:
      aux = p[k]
      p[k] = p[r]
      p[r] = aux
      for j in range(0, n):
        aux = matrix[k][j]
        matrix[k][j] = matrix[r][j]
        matrix[r][j] = aux

    for i in range(k+1, n):
      m = matrix[i][k]/matrix[k][k]
      matrix[i][k] = m
      for j in range(k+1, n):
        matrix[i][j] -= m*matrix[k][j]


  c = n * [0]
  for i in range(0, n):
    r = p[i]
    c[i] = b[r]

  y = n * [0]
  for i in range(0, n):
    soma = 0
    for j in range(0, i):
      soma += matrix[i][j]*y[j]
    y[i] = (c[i] - soma)

  x = n * [0]
  for i in range(n-1, -1, -1):
    soma = 0
    for j in range(i+1, n):
      soma += matrix[i][j]*x[j]
    x[i] = (y[i] - soma)/matrix[i][i]

  for k in matrix:
    print(k)
  print('\n')
  print(f"y: {y}")
  print(f"x: {x}")


magalu(a, b)

#**Gauss-Jacobi**

In [ ]:
import numpy as np
from numpy.linalg import solve

def jacobi(A,b,n):
  x = len(A) * [0]
  D = np.diag(A)
  R = A-np.diagflat(D)
  for i in range(n):
    x = (b-np.dot(R,x))/D
  return x

#print(solve(A,b))
'''A = np.array([[3, -4, 1],
     [1, 2, 2],
     [4, 0, -3]])
b = [9, 3, -2]'''

A = np.array([[4,1,2], [3,5,1], [1,1,3]])
b = [4,7,3]
n = 25
print(jacobi(A,b,n))
print(solve(A,b))

[0.50030249 1.0003236  0.50028352]
[0.5 1.  0.5]


In [ ]:
def criterio_linhas(A):
    swap = np.copy(A)
    b = np.diag(A)
    A = A - np.diagflat(b)
    x = np.ones(b.size)
    permutation = b.size**2
    acc = True
    
    while(acc and permutation > 0):
        for i in range(b.size):
            x[i] = np.sum(A[i])/b[i]
        
        if(np.amax(x) < 1): acc = False
        else:
            permutation = permutation-1
            swap = np.random.permutation(swap)
            A = np.copy(swap)
            b = np.diag(A)
            A = A - np.diagflat(b)
    
    return np.amax(x)

#Matriz A, Matriz b dos termos independentes e N o número de iterações e o erro
def jacobi(A, b, N, chute, erro = 0.00000001):
    if(criterio_linhas(A) > 1):
        print("O sistema não converge para o método de Jacobi")
        return
    
    x = np.diag(A) #recebe um vetor contendo a diagonal principal
    A = A - np.diagflat(x) #Zera a diagonal principal de A
    
    #Para dividir todos os valores da matriz A pelos termos independentes
    for i in range(x.size):
        A[i] = A[i]/x[i]
        b[i] = b[i]/x[i]

    x = np.copy(chute)
    swap = np.zeros(x.size)
    
    A = A*-1
    
    for stop in range(N):
        for i in range(x.size):
            swap[i] = np.sum((A[i]*x))+(b[i])
        #Cálculo da tolerância ou erro
        print(f"Iteração {stop}: {swap}")
        if((np.linalg.norm(swap) - np.linalg.norm(x)) < erro): return swap
        x = np.copy(swap)

    return x

'''A = np.array([[3, -4, 1],
     [1, 2, 2],
     [4, 0, -3]])
b = [9, 3, -2]
x= [1, 1, 1]'''


A = np.array([[4,1,2], [3,5,1], [1,1,3]])
b = [4,7,3]
print(solve(A,b))
x = [1, 1, 1]
n = 1
print(jacobi(A, b, n, x))

[0.5 1.  0.5]
Iteração 0: [1.  1.4 1. ]
[1.  1.4 1. ]


#**Gauss-Seidel**

In [ ]:
def update_solution(
    coefficient_matrix, solution_vector, constant_vector
):
    """
    Function to update the solution
    :param coefficient_matrix: list, Coefficient Matrix
    :param solution_vector: list, Solution Vector
    :param constant_vector: list, Constant Vector
    :return: list, Updated Solution Vector
    Example:
a = [[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]]
    >>> x = [0, 0, 0, 0]
    >>> b = [6, 25, -11, 15]
    >>> update_solution(a, x, b)
    [0.6, 2.3272727272727276, -0.9872727272727271, 0.8788636363636363]
    """
    n = len(coefficient_matrix)  # number of variables
    for i in range(0, n):
        # Update each variable
        d = constant_vector[i]
        for j in range(0, n):
            if i != j:
                d -= coefficient_matrix[i][j] * solution_vector[j]
        solution_vector[i] = d / coefficient_matrix[i][i]
    return solution_vector

def gauss_seidel(
    coefficient_matrix,
    solution_vector,
    constant_vector,
    maximum_iterations,
):
    """
    Function to perform Gauss Seidel Iteration
    :param coefficient_matrix: list, Coefficient Matrix
    :param solution_vector: list, Solution Vector
    :param constant_vector: list, Constant Vector
    :param maximum_iterations: int, Maximum Iterations
    :return: None
    Example:
a = [[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]]
    >>> x = [0, 0, 0, 0]
    >>> b = [6, 25, -11, 15]
    >>> gauss_seidel(a, x, b, 100)
    [1.0, 2.0, -1.0, 1.0]
    """

    for i in range(0, maximum_iterations):
        solution_vector = update_solution(
            coefficient_matrix, solution_vector, constant_vector
        )
        # print("Iteration {}: {}".format(i, x))
    return solution_vector

# a = [[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]]
# x = [0, 0, 0, 0]
# b = [6, 25, -11, 15]
'''A = np.array([[3, -4, 1],
     [1, 2, 2],
     [4, 0, -3]])'''
#b = [4,7,3]

a = [[4,1,2], [3,5,1], [1,1,3]]
x = [0, 0, 0]
b = [4,7,3]
n = 25
print(gauss_seidel(a, x, b, 100))

[0.5, 1.0, 0.5]


In [ ]:
def differentiateFunction(x, f, dx = 0.00000001):
  return (f(x + dx) - f(x)) / dx

print(differentiateFunction(1, lambda x: (2**x) + 1))

1.3862943681886009
