In [ ]:
import numpy as np
print("Método de Gauss Jacobi")

def max(A):#retorna o maior valor absoluto de uma matrix
    max=A[0][0]
    for i in range(len(A)):
        for j in range(len(A[0])):
            if abs(A[i][j]) >max:
                max=abs(A[i][j])
    return max

while True:
    n =(input("Tamanho da Matriz:\n"))
    if n.isdigit():
        n=int(n)
        break
    else:
        print("Entrada inválida, tente novamente!")
e=float(input("Qual a precisão desejada?"))

A=np.zeros((n,n))#A matriz A
B=np.zeros((n, 1))#O vetor coluna b de Ax=b
C=np.zeros((n,n))#A matriz C  de Cx + G
G=np.zeros((n,1))# o vetor coluna G de Cx + G
X=np.zeros((n, 1))#o vetor x de Ax=B

#Definindo a matriz A
for i in range(n):
        while True:
            print("Digite os elementos da linha ", i + 1, " da matriz A separados por espaço:", end="")
            l = input().split()
            if len(l) == n:
                break
            else:
                print("Entrada inválida, tente novamente!")
        for j in range(len(l)):
            A[i][j] = float(l[j])


# definir vetor b

while True:
    print("Digite os elementos do vetor B de Ax=b separados por espaço:", end=" ")
    l = input().split()
    if len(l) == n:
        break
    else:
        print("Entrada inválida, tente novamente!")
for k in range(len(l)):
    B[k][0]=float(l[k])


while True:
    print("Digite os elementos do vetor inicial X0 separados por espaço:", end=" ")
    l = input().split()
    if len(l) == n:
        break
    else:
        print("Entrada inválida, tente novamente!")
for k in range(len(l)):
    X[k][0]=float(l[k])

#Testando o critério de convergência
D=np.zeros((n,1))#Vetor alfa da página 123 do slide
for i in range(n):
    soma=0
    l = list(range(n))
    l.remove(i)  # aqui eu quero que percorra todos os elemento da coluna exceto o próprio elemento
    for j in l:
        soma+=A[i][j]
    D[i][0]=abs(soma/A[i][i])

if max(D) <1:
    print("A matriz atende ao critério de convergência")
else:
    print("A matriz não atende ao critério de convergencia mas não necessarimente não convergirá")

#Criando a matriz C de  Cx+G
for i in range(n):
    for j in range(n):
        if i == j:
            C[i][j]=0
        else:
            if A[i][i]!=0:
                C[i][j]=-A[i][j]/A[i][i]
            else:
                print("Divisão por zero!")
                break
    if A[i][i]!=0:
        G[i][0]=B[i][0]/A[i][i] #Colocando os valores de G


#Fazendo as iterações
ni=0#contador do numero de iterações
while True:
    ni+=1
    Xk=np.dot(C,X) + G#Aqui eu faço X(k+1)=C*Xk+G
    d=max(Xk-X)/max(Xk)
    if d <e:
        break
    else:
        X=Xk
# imprimindo a Matriz A
print("Matriz A")
for i in range(n):
    print(A[i])

# imprimindo a Matriz C
print("Matriz C")
for i in range(n):
    print(C[i])

# imprimindo vetor G
print("Vetor G")
for i in range(n):
    print(G[i])

# imprimir solucao
print('solução do sistema linear dado:')
for i in range(n):
    print('x%o = ' % (i + 1), Xk[i][0])
print("Numero de iterações = ",ni)

Método de Gauss Jacobi
Tamanho da Matriz:
3
Qual a precisão desejada?0.00000001
Digite os elementos da linha  1  da matriz A separados por espaço:4 1 2
Digite os elementos da linha  2  da matriz A separados por espaço:3 5 1
Digite os elementos da linha  3  da matriz A separados por espaço:1 1 3
Digite os elementos do vetor B de Ax=b separados por espaço: 4 7 3
Digite os elementos do vetor inicial X0 separados por espaço: 1 1 1
A matriz atende ao critério de convergência
Matriz A
[4. 1. 2.]
[3. 5. 1.]
[1. 1. 3.]
Matriz C
[ 0.   -0.25 -0.5 ]
[-0.6  0.  -0.2]
[-0.33333333 -0.33333333  0.        ]
Vetor G
[1.]
[1.4]
[1.]
solução do sistema linear dado:
x1 =  0.5000000037290776
x2 =  1.0000000039893089
x3 =  0.5000000034952189
Numero de iterações =  60


In [ ]:
#eliminação de gauss
import numpy as np

def  troca_linha(A,k,i):#Na matriz A troca de lugar a linha k com a linha i
    b = np.copy(A[i])
    A[i] = np.copy(A[k])
    A[k] = np.copy(b) #A[k] recebe A[i]
    return A

def gauss_step(A,k):
    for i in range(k+1,n):#i está sempre 1 unidade a frente de k, já q i=k+1
        m=-A[i][k]/A[k][k]
        A[i] = A[i] + m * A[k]# aqui ele faz a multiplicação de toda a linha i pelo fator m achado anteriormente

    return A

# triangle form, without care and pivoting
def triangle_form(A):#método que fará o escalonamento
    for k in range(len(A)):
        p=1#apenas para condicionar o próximo while
        while p:

            if A[k][k] != 0:
                A=gauss_step(A,k)
                break
            else:  #Se o programa encontra um zero na diagonal principal ele tenta achar um numero abaixo dele na minha coluna diferente de zero para fazer a troca de linhas
                print( ' falha ')
                if k==n-1:
                    break
                else:
                    for i in range(k+1,n):
                        if A[i][k]!=0:
                            print("troca da linha ", k+1 ," pela linha ",i+1)
                            troca_linha(A,k,i)
                            break
                        elif i==n-1:
                            p=0#apenas para encerrar o while
    return A

n =int(input("Tamanho da Matriz:\n"))

#Definindo a matriz A
A=np.zeros((n,n+1))
for i in range(n):
        while True:
            print("Digite os elementos da linha ", i + 1, " separados por espaço:", end="")
            l = input().split()
            if len(l) == n:
                break
            else:
                print("Entrada inválida, tente novamente!")
        for j in range(len(l)):
            A[i][j] = float(l[j])

# definir a matriz Ab de Ax=b
while True:
    print("Digite os elementos do vetor B de Ax=b separados por espaço:", end=" ")
    l = input().split()
    if len(l) == n:
        break
    else:
        print("Entrada inválida, tente novamente!")
for k in range(len(l)):
    A[k][n]=float(l[k])

np.set_printoptions(suppress=True, precision=4)#apenas para melhorar a impressão das matrizes
#Escalonando a matriz aumentada Ab
B=triangle_form(A)

print("Nova matriz A^(",n,") escalonada: ")
print(A.transpose()[:n].transpose())
print("Novo vetor A^(",n,") escalonado")
print(A.transpose()[n:].transpose())

# definir vetor b
b = np.empty([n])
for i in range(n):
    b[i]=A[i][n]

# Resolver sistema Ax = b
for i in range(1, n):
    # definir vetor (solucao) x
    x = np.empty([n])
    x[n - 1] = b[n - 1] / A[n - 1][n - 1]
    for i in range(n - 2, -1, -1):
        soma = 0
        for j in range(i + 1, n):
            soma += A[i][j] * x[j]

        x[i] = (b[i] - soma) / A[i][i]

# imprimir solucao
print('solucao do sistema linear dado:')
for i in range(n):
    print('x%i = ' % (i + 1), x[i])

In [ ]:
from random import randint

print("Programa para decomposição LU")
while True:
    n = int(input("Tamanho da Matriz:\n"))
    x = "m"  # input("Adicionar elementos manualmente ou randomicamente?\nM para manualmente\nR para randomicamente\n")
    vetorB = []
    vetorY = []
    vetorX = []
    matrizA = []  # Matriz A
    matrizL = []  # Matriz L
    matrizU = []  # Matriz U
    cd = 5  # numero de casa decimais para arredondamento

    # Criando a matriz L e U nxn
    for i in range(n):
        matrizL.append([0.0] * n)
        matrizU.append([0.0] * n)
        vetorY.append([0])
        vetorX.append(([0]))

    # Criando a matriz A e vetores X e Y
    for i in range(n):
        if x.lower() == "m":
            while True:
                print("Digite os elementos da linha ", i + 1, " separados por espaço:", end="")
                l = input().split()
                if len(l) == n:
                    break
                else:
                    print("Entrada inválida, tente novamente!")
            for k in range(len(l)):
                l[k] = float(l[k])
            matrizA.append(l)
        else:
            matrizA.append([0] * n)
            for j in range(n):
                matrizA[i][j] = randint(0, 3)

    # testando se o primeiro elemento da matriz é igual a zero
    if matrizA[0][0] == 0:
        # imprimindo a matriz A
        print("Matriz A")
        for i in range(n):
            print(matrizA[i])
        print(
            "O primeiro elemento da matriz é igual a zero o que causará uma divisão por zero ao calcular a primeira linha de L")
        break

    # criando o vetor B
    if x.lower() == "m":
        # criando o vetor B
        while True:
            print("Digite os elementos do vetor B separados por espaço:", end=" ")
            l = input().split()
            if len(l) == n:
                break
            else:
                print("Entrada inválida, tente novamente!")
        for k in range(len(l)):
            vetorB.append([float(l[k])])
    else:
        for k in range(n):
            vetorB.append([randint(0, 50)])

    # imprimindo a matriz A
    print("Matriz A")
    for i in range(n):
        print(matrizA[i])


    # primeira linha de U e diagonal principal de L
    for i in range(n):
        matrizU[0][i] = matrizA[0][i]
        matrizL[i][i] = 1.0
    # primeira coluna de L

    for i in range(1, n):
        matrizL[i][0] = matrizA[i][0] / matrizU[0][0]
    # segunda linha de U

    for i in range(1, n):
        matrizU[1][i] = matrizA[1][i] - matrizL[1][0] * matrizU[0][i]

    # O resto das fileiras de L e U
    if n > 2:
        for j in range(1,
                       n - 1):  # começo por 1 por que a primeira linha e coluna de U e L respectivamente já foram definidas antes desse bloco
            # fazendo próxima coluna de L
            for i in range(j + 1,
                           n):  # i = começa em j + 1 por que quando eu  estou na segunda coluna de L eu devo começar pela terceira linha, já que a segunda é igual a 1 e a primeira igual a 0
                soma = 0
                for k in range(j):
                    soma += matrizL[i][k] * matrizU[k][j]
                if matrizU[j][j] != 0:
                    matrizL[i][j] = (matrizA[i][j] - soma) / matrizU[j][j]
            # fazendo próxima linha de U
            for i in range(j + 1, n):
                soma = 0
                for k in range(n - 1):
                    soma += matrizL[j + 1][k] * matrizU[k][i]
                matrizU[j + 1][i] = matrizA[j + 1][i] - soma


        # imprimindo a matriz L
        print("Matriz L")
        for i in range(n):
            print(matrizL[i])

        # imprimindo a matriz U
        print("Matriz U")
        for i in range(n):
            print(matrizU[i])

        # imprimindo vetor b
        p = []
        for i in range(n):
            p.append(vetorB[i][0])
        print("Vetor B")
        print(p)

        # Resolver o sistema Ly=b
        vetorY[0][0] = vetorB[0][0]
        for i in range(1, n):
            soma = 0
            for j in range(i):
                soma += matrizL[i][j] * vetorY[j][0]
            vetorY[i][0] = vetorB[i][0] - soma
        # Resolver o sistema Ux=b
        vetorX[n - 1][0] = round(vetorY[n - 1][0] / matrizU[n - 1][n - 1], cd)
        for i in range(n - 1, -1, -1):
            soma = 0
            for j in range(i + 1, n):
                soma += matrizU[i][j] * vetorX[j][0]
            vetorX[i][0] = round((vetorY[i][0] - soma) / matrizU[i][i], cd)
        print("Solução do Sistema linear:")
        for i in range(n):
            print("X", i + 1, " = ", round(vetorX[i][0],cd))
    else:
        print("A matriz não atende ao Teorema LU")
    acabar = input("Tecle ENTER resolver outro sistema e digite F para finalizar o programa: ")
    if acabar.lower().strip() == "f":
        break



Programa para decomposição LU
Tamanho da Matriz:
3
Digite os elementos da linha  1  separados por espaço:4 1 2
Digite os elementos da linha  2  separados por espaço:3 5 1
Digite os elementos da linha  3  separados por espaço:1 1 3
Digite os elementos do vetor B separados por espaço: 4 7 3
Matriz A
[4.0, 1.0, 2.0]
[3.0, 5.0, 1.0]
[1.0, 1.0, 3.0]
Matriz L
[1.0, 0.0, 0.0]
[0.75, 1.0, 0.0]
[0.25, 0.17647058823529413, 1.0]
Matriz U
[4.0, 1.0, 2.0]
[0.0, 4.25, -0.5]
[0.0, 0.0, 2.588235294117647]
Vetor B
[4.0, 7.0, 3.0]
Solução do Sistema linear:
X 1  =  0.5
X 2  =  1.0
X 3  =  0.5
Tecle ENTER resolver outro sistema e digite F para finalizar o programa: f


In [ ]:
import math
print("Método de Newton")
print("Qual a aproximação inicial X0 e a precisão e?")
x0=float(input("Entre com x0"))
e=float(input("Entre com e"))
i=0
cd=30 #numero de casa decimais para arredondamento de Wx
def Fx(x):# Função
    Fx=math.exp(-x**2+1)+math.sin(x**2)-x
    return Fx
def Wx(x): # Função de interação
    Wx=x-(math.exp(-x**2+1)+math.sin(x**2)-x)/(-2*x*math.exp(-x**2+1)+math.cos(x**2)*2*x-1)
    return Wx
#Fazendo as iterações
while True:
    i+=1
    x=Wx(x0)
    if abs(Fx(x)) < e or abs(x-x0)<e:
        break
    else:
        x0=x
print("Raiz = ",x)
print("Iterações = ",i)

In [ ]:
import math
print("Método da Posição Falsa")
def funcao(x):
    fx = math.exp(-x**2+1)+math.sin(x**2)-x
    return fx
print("Qual o intervalo [a,b] da raiz e a precisão e?")
a =float(input("Entre com a: "))
b =float(input("Entre com b: "))
e =float(input("Entre com e: "))
i = 0
while True:
    i+=1
    fxa=funcao(a)
    fxb=funcao(b)
    x=(a*fxb-b*fxa)/(fxb-fxa)
    fx=funcao(x)
    if abs(fxa) < e:
        x=a
        break
    elif abs(fxb) < e:
        x=b
        break
    elif abs(fx) < e:
        break
    elif fxa*fx<0:
        b=x
    elif fxa*fx >0:
        a=x
    elif b-a<e:
        x=(b+a)/2
print("Raiz =",x)
print("Iterações = ",i)

In [ ]:
import math
print("Método do Ponto Fixo")
print("Qual a aproximação inicial X0 e a precisão e?")
x0=float(input("Entre com o numero real x0: "))
e=float(input("Entre com o numero real e: "))
i=0
def Fx(x):#Função
    fx=math.exp(-x**2+1)+math.sin(x**2)-x
    return fx
def Wx(x):#Função de iteração
    Wx=((math.exp(-x**2+1)+math.sin(x**2)-x)+2*x)/2
    return Wx
while True:
    i+=1
    x1=Wx(x0)
    if abs(Fx(x1)) < e or abs(x1-x0) <e:
        print("x = ", x1)
        print("Número de iterações =", i)
        break
    x0=x1

In [ ]:
import math
print("Método da Bisseção")
def funcao(x): #Aqui é onde você deve colocar a função fx
        fx=(1/48)*(693*x**6-945*x**4+315*x**2-15)#defini uma função arbitrariamente
        return fx
print("Qual o intervalo [a,b] da raiz e a precisão e?")
a=float(input("Entre com o inicio do intervalo: "))#inicio do intervalo
b=float(input("Entre com o fim do intervalo: "))#fim do intervalo
e=float(input("Entre com a precisão desejada: "))#precisão
i=0#contador
k=(math.log10(b-a)-math.log10(e)/math.log10(2))#fórmula para estimar o número de interações
k=math.ceil(k) #função ceil arredonda pra cima
print("Numero estimado de iterações: ",k)
if b-a<e:# se o intervalo a b for menor q a precisão o programa acaba pegando o valor médio de a b
    x=(a+b)/2
    print("Raiz:", x)
else:
    while True:
        i+=1#incrementa o contador para medir o número de iterações
        x=(a+b)/2 #pega x como o ponto central do intervalo a b
        fxa=funcao(a)#calcula fx no ponto a
        fxb=funcao(b)#calcula fx no ponto b
        fx=funcao(x) #calcula fx no ponto x
        if fx==0.0:#se fx de x for menor q a precisão o programa acabar pegando x como resposta
            print("Raiz: ",x)
            break
        elif fxa*fx<0: #verifica se houve troca de sinal no valor de y a de a para x, se sim x é novo b
            b=x
        elif fxa*fx>0:#caso contrário x é o novo a
            a=x
        if b-a<e: # se o intervalo a b for menor q a precisão o programa acaba pegando o valor médio de a b
            x = (a + b) / 2
            print("Raiz:", x)
            print("Numero de iterações = ",i)
            break